CREATE TABLE USER
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '고유 아이디',
    USERNAME    varchar(80)  NOT NULL COMMENT '아이디',
    PASSWORD    varchar(500) NOT NULL COMMENT '비밀번호',
    ROLE_NAME   varchar(50) NOT NULL COMMENT '권한 이름',
    CREATE_DT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    UPDATE_DT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경 시간',
    PRIMARY KEY (ID)
) COMMENT '회원 정보';